config/routes.rb
Rails.application.routes.draw do
  post 'like/:id', to: 'posts#like', as: 'like'
  delete 'unlike/:id', to: 'posts#unlike', as: 'unlike'
  
  post 'like_comment/:comment_id', to: 'posts#like_comment', as: 'like_comment'
  delete 'unlike_comment/:comment_id', to: 'posts#unlike_comment', as: 'unlike_comment'
  
  post 'like_reply/:reply_id', to: 'comments#like_reply', as: 'like_reply'
  delete 'unlike_reply/:reply_id', to: 'comments#unlike_reply', as: 'unlike_reply'
  
  post 'comment', to: 'posts#comment', as: 'comment'

  post 'reply', to: 'comments#reply', as: 'comment_reply'
  delete 'destroy_reply/:reply_id', to: 'comments#destroy_reply', as: 'destroy_reply'

  resources :posts do
    resources :comments 
  end
  devise_for :users
  root "home#index"
  get 'about', to: 'home#about'

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :comment_likes, foreign_key: 'comment_id', dependent: :destroy
  has_many :comment_replies, foreign_key: 'comment_id', dependent: :destroy
  validates :content, presence: true
  def count_likes
    count = CommentLike.where(comment: self).count
    if count == 1
      "#{count} Like"
    elsif count.zero?
      'No Likes'
    else
      "#{count} Likes"
    end
  end

  def count_replies
    count = CommentReply.where(comment: self).count
    if count == 1
      "#{count} Reply"
    elsif count.zero?
      'No Replies'
    else
      "#{count} Replies"
    end
  end
end
return

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(post_id: params[:post_id], id: params[:id])
    @comment_like = CommentLike.new
    @comment_reply = CommentReply.new
    @comment_replies = CommentReply.where(comment: @comment)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_path(params[:post_id]), notice: 'Comment deleted.'
  end

  def reply
    comment_reply = CommentReply.new(reply_params)
    comment_reply.user = current_user
    flash[:notice] = if comment_reply.save
                       'You replied on the comment'
                     else
                       comment_reply.errors.full_messages.join(', ')
                     end
    redirect_to request.referrer
  end

  def destroy_reply
    comment_reply = CommentReply.find(params[:reply_id])
    authorize! :destroy_reply, comment_reply # custom action
    comment_reply.destroy
    redirect_to request.referrer, notice: 'Reply deleted.'
  end

  def like_reply
    reply = CommentReply.find(params[:reply_id])
    like = ReplyLike.new(comment_reply: reply, user: current_user)
    like.save
    redirect_to request.referrer
  end

  def unlike_reply
    like = ReplyLike.find_by(comment_reply: params[:reply_id], user: current_user)
    like.destroy
    redirect_to request.referrer
  end

  private

  def reply_params
    params.require(:comment_reply).permit(:comment_id, :content)
  end

  def reply_like_param
    params.require(:reply_like).permit(:comment_reply_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end
return

app/views/comments/_card.html.erb
    
<div class="comment-card">
  <div class="comment-text">
    <b style="color: #219ebc"><%= truncate(comment.user.username, length: 10, omission: '...')%>;</b>
    <em>❝ <%= comment.content %> ❞</em>
  </div>
  <div class="writer-name">
    <%= comment.count_likes %> | <%= comment.count_replies %>
  </div>
  <div class="likes-container">
  <% if user_signed_in? %>
    <% if CommentLike.find_by(comment: comment, user: current_user) %>
      <%= button_to unlike_comment_path(comment.id), method: :delete, class: 'icon-container comment' do %>
        <%= image_tag "unlike.svg", height: 20, class: 'active-like'  %>
      <% end %>
    <% else %>
      <%= button_to like_comment_path(comment.id), method: :post, class: 'icon-container comment' do %>
        <%= image_tag "like.svg", height: 20, class: 'active-like' %>
        <%= image_tag "hover-like.svg", height: 20, class: 'hover-like' %>
      <% end %>
    <% end %>
  <% end %>
    <% unless no_reply %>
      <%= link_to post_comment_path(@post, comment), class: 'icon-container comment' do %>
        <%= image_tag "comment.svg", height: 20 %>
      <% end %>
    <% end %>
    <% if can? :destroy, comment %>
      <%= button_to post_comment_path(@post, comment), method: :delete, class: 'icon-container comment'  do %>
        <%= image_tag "delete.svg", height: 20 %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/show.html.erb
<%= link_to "Back", post_path(@post), class: 'back-link' %>
<div class="post-container">
  <%= render 'comments/card', posts: @posts, comment: @comment, no_reply: true %>
  <% if user_signed_in? %>
    <%= form_with model: @comment_reply, url: comment_reply_path, html: { class: 'post-form' }  do |f| %>
      <%= f.hidden_field :comment_id, value: @comment.id %>
      <% f.label :content %>
      <%= f.text_area :content, class: 'text-area comment' %>
      <%= f.submit "Reply", class: 'submit' %>
    <% end %>
  <% end %>
  <% @comment_replies.each do |comment_reply|%>
    <div class="reply-card">
      <div class="comment-text">
        <b style="color: #219ebc"><%= truncate(comment_reply.user.username, length: 10, omission: '...')%>;</b>
        @<%= comment_reply.comment.user.username%>
        <em>❝ <%= comment_reply.content %> ❞</em>
      </div>
      <div class="writer-name">
        <%= comment_reply.count_likes %>
      </div>
      <div class="likes-container">
      <% if user_signed_in? %>
        
        <% if ReplyLike.find_by(comment_reply: comment_reply, user: current_user) %>
          <%= button_to unlike_reply_path(comment_reply.id), method: :delete, class: 'icon-container comment' do %>
            <%= image_tag "unlike.svg", height: 20, class: 'active-like'  %>
          <% end %>
        <% else %>
          <%= button_to like_reply_path(comment_reply.id), method: :post, class: 'icon-container comment' do %>
            <%= image_tag "like.svg", height: 20, class: 'active-like' %>
            <%= image_tag "hover-like.svg", height: 20, class: 'hover-like' %>
          <% end %>
        <% end %>
      <% end %>
        <% if can? :destroy_reply, comment_reply %>
          <%= button_to destroy_reply_path(comment_reply), method: :delete, class: 'icon-container comment'  do %>
            <%= image_tag "delete.svg", height: 20 %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>