config/routes.rb
Rails.application.routes.draw do
  post 'like/:id', to: 'posts#like', as: 'like'
  delete 'unlike/:id', to: 'posts#unlike', as: 'unlike'
  
  post 'like_comment/:comment_id', to: 'posts#like_comment', as: 'like_comment'
  delete 'unlike_comment/:comment_id', to: 'posts#unlike_comment', as: 'unlike_comment'
  
  post 'like_reply/:reply_id', to: 'comments#like_reply', as: 'like_reply'
  delete 'unlike_reply/:reply_id', to: 'comments#unlike_reply', as: 'unlike_reply'
  
  post 'comment', to: 'posts#comment', as: 'comment'

  post 'reply', to: 'comments#reply', as: 'comment_reply'
  delete 'destroy_reply/:reply_id', to: 'comments#destroy_reply', as: 'destroy_reply'

  resources :posts do
    resources :comments 
  end
  devise_for :users
  root "home#index"
  get 'about', to: 'home#about'

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_likes, foreign_key: 'post_id', dependent: :destroy
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true

  def count_likes
    count = PostLike.where(post: self).count
    if count == 1
      "#{count} Like"
    elsif count.zero?
      'No Likes'
    else
      "#{count} Likes"
    end
  end

  def count_comments
    comments = Comment.where(post: self)
    count = comments.count
    comments.each do |comment|
      count += CommentReply.where(comment:).count
    end
    if count == 1
      "#{count} Comment"
    elsif count.zero?
      'No Comments'
    else
      "#{count} Comments"
    end
  end
end
return

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def index
    @posts = Post.where('public = true').order(created_at: :desc).limit(100)
    render json: @posts.map { |p|
                   {
                     id: p.id,
                     title: p.title,
                     content: p.content,
                     author: p.user.name,
                     likes: p.count_likes,
                     comments: p.comments.map do |c|
                                 {
                                   id: c.id,
                                   comment: c.content,
                                   author: c.user.name,
                                   likes: c.count_likes,
                                   replies: c.comment_replies.map do |r|
                                              {
                                                id: r.id,
                                                reply: r.content,
                                                author: r.user.name,
                                                likes: r.count_likes
                                              }
                                            end
                                 }
                               end
                   }
                 }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def index
    @posts = if user_signed_in?
               Post.where('public = ? OR user_id = ? OR ?', true, current_user.id,
                          current_user.role == 'admin').order(created_at: :desc).limit(100)
             else
               Post.where('public = true').order(created_at: :desc).limit(100)
             end
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.user = current_user
    if post.save
      flash[:notice] = 'Post is live'
      redirect_to posts_path
    else
      flash[:notice] = post.errors.full_messages.join(', ')
      redirect_to request.referrer
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: 'Post deleted.'
  end

  def update
    post = Post.find(params[:id])
    post.public = if post.public
                    false
                  else
                    true
                  end
    flash[:notice] = (comment.errors.full_messages.join(', ') unless post.save)
    redirect_to request.referrer
  end

  def show
    @post = Post.find(params[:id])
    @like_text = 'Like'
    @like_text = 'Unlike' if PostLike.find_by(post: @post, user: current_user)
    @post_like = PostLike.new
    @comment_like = CommentLike.new
    @comments = Comment.where(post: @post)
    @comment = Comment.new
  end

  def like
    post = Post.find(params[:id])
    like = PostLike.new(post:, user: current_user)
    like.save
    redirect_to request.referrer
  end

  def unlike
    like = PostLike.find_by(post: params[:id], user: current_user)
    like.destroy
    redirect_to request.referrer
  end

  def comment
    comment = Comment.new(comment_params)
    comment.user = current_user
    flash[:notice] = if comment.save
                       'You commented on the post'
                     else
                       comment.errors.full_messages.join(', ')
                     end
    redirect_to request.referrer
  end

  def like_comment
    comment = Comment.find(params[:comment_id])
    like = CommentLike.new(comment:, user: current_user)
    like.save
    redirect_to request.referrer
  end

  def unlike_comment
    like = CommentLike.find_by(comment: params[:comment_id], user: current_user)
    like.destroy
    redirect_to request.referrer
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :public)
  end

  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end
return

app/views/posts/_cards.html.erb
<div class="posts-container">
  <% @posts.each_with_index  do |post, index|%>
    <%= link_to post_path(post) do %>
      <div class="post-card">
        <section class="post-header">
          <span class="post-user">
            <%= truncate(post.user.name, length: 10, omission: '... ') %>:
          </span>
          <span class="post-title">
            <%= truncate(post.title, length: 20, omission: '...') %>
          </span>
        </section>
        <p class="post-content"  style="<%= "text-align: right;" if post.content[0].match?(/\p{Arabic}/) %>">
          <%= truncate(post.content, length: 100, omission: '...') %>
        </p>
        <span class="writer-name">
          <%= post.count_likes %> | <%= post.count_comments %>
        </span>
        <section class="post-footer">
          <% if user_signed_in? && current_user.id == post.user.id %>
            <span class="mine-tag tag">
              #mine
            </span>
          <% end %>
          <% if user_signed_in? && !post.public && (current_user.role == 'admin' || current_user.id == post.user.id) %>
            <span class="private-tag tag">
              #private
            </span>
          <% end %>
        </section>
      </div>
    <% end %>
    <div class="ad-unit">
    <% if index % 3 == 0 %>
      <%= render 'layouts/ad-card' %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<h2>Posts List</h2>
<%= render 'posts/cards', posts: @posts %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= form_with model: @post, url: posts_path, html: { class: 'post-form' }  do |f| %>

  <%= f.label :title, class: 'hidden'%>
  <%= f.text_field :title, placeholder: "Post Title", class: 'text-field'%>
  <%= f.label :content, class: 'hidden'%>
  <%= f.text_area :content, placeholder: "Post content ...", class: 'text-area' %>
  <div class="check-box-container">
    <%= f.check_box :public, checked: true %>
    <%= f.label :public %>
  </div>
  <%= f.submit "Create Post", class: 'submit' %>
<% end %>

app/views/posts/show.html.erb
<div class="links-container">
  <%= link_to "Back", posts_path, class: 'back-link' %>
  <% if can? :update, @post %>
    <%= "|" %>
    <%= button_to post_path(@post), method: :patch, class: 'back-link link' do
        if @post.public
        "Change to private"
        else
        "Change to public"
        end
      end %>
  <% end %>
  <%= "|" if can? :destroy, @post %>
  <%= button_to "Delete", post_path(@post), method: :delete, class: 'back-link link del-link' if can? :destroy, @post %>
</div>
<h2  style="<%= "text-align: right;" if @post.title[0].match?(/\p{Arabic}/) %>"><%= @post.title %></h2>
<div class="post-container">
  <div class="post-text">
    <span style="<%= "text-align: right;" if @post.content[0].match?(/\p{Arabic}/) %>">
      <%= @post.content.gsub(/\n/, '<br>').html_safe %>
    </span>
    <em class="writer-name">
      Written by <%= @post.user.name %>
    </em>
    <section class="post-footer">
      <% if user_signed_in? && current_user.id == @post.user.id %>
        <span class="mine-tag tag">
          #mine
        </span>
      <% end %>
      <% if !@post.public && (current_user.role == 'admin' || current_user.id == @post.user.id) %>
        <span class="private-tag tag">
          #private
        </span>
      <% end %>
    </section>
  </div >
  <div class="likes-container">
    <% if user_signed_in? %>
      <% if PostLike.find_by(post: @post, user: current_user) %>
        <%= button_to unlike_path(@post.id), method: :delete, class: 'icon-container' do %>
          <%= image_tag "unlike.svg", height: 30, class: 'active-like'  %>
        <% end %>
      <% else %>
        <%= button_to like_path(@post.id), method: :post, class: 'icon-container' do %>
          <%= image_tag "like.svg", height: 30, class: 'active-like' %>
          <%= image_tag "hover-like.svg", height: 30, class: 'hover-like' %>
        <% end %>
      <% end %>
    <% end %>
    <%= @post.count_likes %> |
    <%= @post.count_comments %>
  </div>
  <% if user_signed_in? %>
    
  <%= form_with model: @comment, url: comment_path, html: { class: 'post-form' }  do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <% f.label :content %>
    <%= f.text_area :content, placeholder: 'Write a comment ...', class: 'text-area comment' %>
    <%= f.submit "Comment", class: 'submit' %>
  <% end %>
  <% end %>
  <% @comments.each do |comment|%>
    <%= render 'comments/card', posts: @posts, comment: comment, no_reply: false %>
  <% end %>
</div>